name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: Devops-practice (Act. 1 y 2)

      - name: Run tests
        run: npm test
        working-directory: Devops-practice (Act. 1 y 2)

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version  # Usa docker compose en lugar de docker-compose
  
      - name: Build and run Docker Compose
        run: |
          docker compose up --build -d  # Cambiar docker-compose a docker compose
        working-directory: Devops-practice (Act. 1 y 2)
  
      - name: Run docker tests
        run: docker exec devops-practice-container npm test
  
      - name: Stop and clean Docker Compose
        run: |
          docker compose down  # Cambiar docker-compose a docker compose
        working-directory: Devops-practice (Act. 1 y 2)

      - name: Run security audit
        run: npm audit
        working-directory: Devops-practice (Act. 1 y 2)